### ISSUE TITLE
butt.systems has an invalid TLS certificate

### ISSUE THREAD

**Issue by fennekki** [negatendo/butt.systems#4]
What I tried: https://butt.systems/

What I expected: Butts, but encrypted

What I got: "butt.systems uses an invalid security certificate. The certificate is only valid for the following names:"

**Comment by negatendo** [comment]
Thank you. We plan to support secure butts soon. I hope you don't mind me editing your comment to remove the domain names of the innocent.

**Comment by negatendo** [comment]
I am happy to announce the butts are now encrypted.
